service: user-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  api:
    handler: src/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
